### ISSUE TITLE
Ctrl + D and Ctrl + C -ing  goto  gives traceback in output

### ISSUE THREAD

**Issue by technocake** [technocake/goto#111]
While developing data-migration, and writing end to end tests for it, I notice that 
closing goto when prompted for input with either `Ctrl` + `C` and `Ctrl` + `D`
Gives two unix errors:

1. **EOFError**  (`Ctrl` + `D` )
2. **KeyboardInterrupt** (`Ctrl` + `C`)

**edit:** found two more related errors that may occur in py2 and py3:

1. **RuntimeError**
2. **IOError**

I suppose it would look better if both are catched and let goto exit silently.
how: by wrapping `the_real_goto` in a try except and handling both those exceptions.

`Ctrl` + `D` 
```goto

Ah hoy!
    - Goto detects that your magicwords needs to be migrated.

    This is because earlier versions of goto stored the
    project data in a different way.

    details: https://github.com/technocake/goto/issues/108

    But no worries, it can be done automagically,
    right here right now.

    
Shall goto migrate your data now? [y|n]: Traceback (most recent call last):
  File "/usr/local/bin/the_real_goto.py", line 11, in <module>
    load_entry_point('magicgoto', 'console_scripts', 'the_real_goto.py')()
  File "/Users/technocake/code/goto/goto/the_real_goto.py", line 32, in main
    exit_if_unhealthy()
  File "/Users/technocake/code/goto/goto/the_real_goto.py", line 50, in exit_if_unhealthy
    err = healthcheck()
  File "/Users/technocake/code/goto/goto/gotomagic/utils.py", line 144, in healthcheck
    return handle_unmigrated_data()
  File "/Users/technocake/code/goto/goto/gotomagic/utils.py", line 119, in handle_unmigrated_data
    if prompt_to_migrate_data():
  File "/Users/technocake/code/goto/goto/gotomagic/utils.py", line 100, in prompt_to_migrate_data
    return 'y' in input('Shall goto migrate your data now? [y|n]: ').lower()
EOFError
```

`Ctrl` + `C`
```technocake in ~/code/goto on feature/migrations [!?$] project: goto
$ goto

Ah hoy!
    - Goto detects that your magicwords needs to be migrated.

    This is because earlier versions of goto stored the
    project data in a different way.

    details: https://github.com/technocake/goto/issues/108

    But no worries, it can be done automagically,
    right here right now.

    
Shall goto migrate your data now? [y|n]: ^CTraceback (most recent call last):
  File "/usr/local/bin/the_real_goto.py", line 11, in <module>
    load_entry_point('magicgoto', 'console_scripts', 'the_real_goto.py')()
  File "/Users/technocake/code/goto/goto/the_real_goto.py", line 32, in main
    exit_if_unhealthy()
  File "/Users/technocake/code/goto/goto/the_real_goto.py", line 50, in exit_if_unhealthy
    err = healthcheck()
  File "/Users/technocake/code/goto/goto/gotomagic/utils.py", line 144, in healthcheck
    return handle_unmigrated_data()
  File "/Users/technocake/code/goto/goto/gotomagic/utils.py", line 119, in handle_unmigrated_data
    if prompt_to_migrate_data():
  File "/Users/technocake/code/goto/goto/gotomagic/utils.py", line 100, in prompt_to_migrate_data
    return 'y' in input('Shall goto migrate your data now? [y|n]: ').lower()
KeyboardInterrupt
```

**Comment by technocake** [comment]
#112 shows example of catching this
