### ISSUE TITLE
goto copy not working in linux

### ISSUE THREAD

**Issue by technocake** [technocake/goto#114]
First circleci tests failed on goto copy.
Then a test on a linux server over ssh revealed the same issue.

```
technocake@technobase:~/code/goto$ goto copy code
Traceback (most recent call last):
  File "/usr/local/bin/the_real_goto.py", line 11, in <module>
    load_entry_point('magicgoto', 'console_scripts', 'the_real_goto.py')()
  File "/home/technocake/code/goto/goto/the_real_goto.py", line 37, in main
    output, err = run_command(magic, command, args)
  File "/home/technocake/code/goto/goto/the_real_goto.py", line 79, in run_command
    return commands.copy(magic, args)
  File "/home/technocake/code/goto/goto/commands/copy.py", line 18, in copy
    pyperclip.copy(url)
  File "/home/technocake/.local/lib/python2.7/site-packages/pyperclip/__init__.py", line 616, in lazy_load_stub_copy
    return copy(text)
  File "/home/technocake/.local/lib/python2.7/site-packages/pyperclip/__init__.py", line 301, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/introduction.html#not-implemented-error 
technocake@technobase:~/code/goto$ 
```

I've been trying to install all four recommended mechanisms listed in [pyperclip documentation](https://pyperclip.readthedocs.io/en/latest/introduction.html#not-implemented-error) . 

This needs to be investigated further. 
Perhaps using another clipboard lib or finding the linux cause.

The exception should probably be handled and turned into a GotoWarning

**Comment by Arxcis** [comment]
> The exception should probably be handled and turned into a GotoWarning

Why would this not be a `GotoError`. How do you differentiate the two?

**Comment by technocake** [comment]
+1 for `GotoError`  - this is an error outside the system around goto.
