### ISSUE TITLE
goto add - IOError: [Errno 13] Permission denied: '~/.goto/projects/goto.json'

### ISSUE THREAD

**Issue by Arxcis** [technocake/goto#27]
**Terminal Output**
```
jonas in ~/git/technocake/goto on master
$ goto add reddit.space https://www.reddit.com/r/spacex
Traceback (most recent call last):
  File "/usr/local/opt/goto/the_real_goto.py", line 61, in <module>
    magic.save()
  File "/usr/local/opt/goto/gotomagic/magic.py", line 28, in save
    save_magic(self.jfile, self.magic)
  File "/usr/local/opt/goto/gotomagic/magic.py", line 171, in save_magic
    with open(jfile, 'w+') as f:
IOError: [Errno 13] Permission denied: '/home/jonas/.goto/projects/goto.json'
```

**Recording**
https://asciinema.org/a/uuT7vQ4GgXN159wqJ2FP8NprQ

**Comment by technocake** [comment]
pls try to delete ~/.goto and run uninstall again. It seems the system is in a messy state from earlier installs where the installer wasnt quite working

**Comment by Arxcis** [comment]
Tried to do this and it still gives me the same error

**Comment by technocake** [comment]
committ https://github.com/technocake/goto/commit/bc8cad7c7798c2c029b9230a556fd664a2e7553d  fixes this now.
