### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by Arxcis** [technocake/goto#88]
Bug found on `develop` branch
[![asciicast](https://asciinema.org/a/VdfotyP0VsDEs2PJCu8gTW9oq.svg)](https://asciinema.org/a/VdfotyP0VsDEs2PJCu8gTW9oq)

```
bash-3.2$ goto list
article.as-we-may-think
code
downloads
file.goto
folder
gif
git.goto
github
github.goto
goto
home
issues
localgif
music.bruno-mars
newissue
pulls
repo
steam.downloads
steam.games
steamfriends
tesseract
toggl
universe
bash-3.2$ goto issue

Ah hoy!

    - The Magic word issue does not exist.

    Are you sure it exists in the project you are in now?
    Type:

        goto list

    to see all shortcuts in this project.
    
Traceback (most recent call last):
  File "/usr/local/bin/the_real_goto.py", line 11, in <module>
    load_entry_point('magicgoto', 'console_scripts', 'the_real_goto.py')()
  File "/Users/jonasjso/git/github/technocake/goto/goto/the_real_goto.py", line 33, in main
    output, err = run_command(magic, command, args)
  File "/Users/jonasjso/git/github/technocake/goto/goto/the_real_goto.py", line 82, in run_command
    return commands.default(magic, command)
  File "/Users/jonasjso/git/github/technocake/goto/goto/commands/default.py", line 16, in default
    if is_file(url):
  File "/Users/jonasjso/git/github/technocake/goto/goto/gotomagic/utils.py", line 21, in is_file
    candidate = os.path.abspath(raw_uri)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 367, in abspath
    if not isabs(path):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by technocake** [comment]
Interesting - I can't seem to reproduce. 
Did you run `make install` and still have the same issue with `goto issue`?

**Comment by technocake** [comment]
.. I actually checked out `develop` and ran `make install` myself and I can reproduce this bug.

The PR #90 is fixing this :)

**Comment by Arxcis** [comment]
Thank you for #90 ! Case closed 👍
